server:
  port: 8762
spring:
  application:
    name: nativeconfigservice
  profiles:
    active: native //本地
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared