server:
  port: 8900
eureka:
  instance:
    prefer-ip-address: true #表示注册时，使用ip注册，而不是使用主机名称
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka
spring:
  application:
    name: ribbon